services:
  postgres:
    container_name: 'moula-manager-postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USER}'
    ports:
      - '${DATABASE_PORT}'
