name: CI

on:
  push:
    branches: [ "master" ]
    
env:
  MIRROR_URL: "git@github.com:EpitechMscProPromo2025/T-DEV-700-PAR_1.git"

jobs:
  push_to_mirror:
    name: Push to Epitech repository
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == "push"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cloning to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
